### ISSUE TITLE
Customize the look of ERDDAP for OOI

### ISSUE THREAD

**Issue by rsignell-usgs** [rsignell-usgs/ooici-erddap#10]
I find it confusing when all the ERDDAPs have the same NOAA banner at the top.

Consider customizing it with OOI logo (and ICON!) via the instructions here:
http://coastwatch.pfeg.noaa.gov/erddap/download/setup.html#customize

**Comment by tjcrone** [comment]
I very much agree with this. It is very confusing, and it's a pretty confusing page, although I do like the information density. My sense is that the sooner this is made "OOI's" by changing some logos and whatnot, the better.

**Comment by kerfoot** [comment]
I don't have the required privs to do this.  This request has been forwarded onto the Rutgers OOI CI team for their review.  Will let you know what they decide.

**Comment by kerfoot** [comment]
@rsignell-usgs @tjcrone The OOI CI team added an OOI banner to the ERDDAP pages:

https://erddap-uncabled.oceanobservatories.org/uncabled/erddap/index.html

Will this suffice or would you rather it looked like the OMS++ ERDDAP banner?

**Comment by tjcrone** [comment]
That looks nice. What does the OMS++ banner look like?

**Comment by kerfoot** [comment]
@tjcrone <img width="1440" alt="screen shot 2017-09-21 at 4 23 42 pm" src="https://user-images.githubusercontent.com/2778797/30716889-5b7660b6-9ee9-11e7-83ad-d15ed7493e67.png">

**Comment by tjcrone** [comment]
I vote for the smaller one, but I don't have a strong opinion.

**Comment by kerfoot** [comment]
@tjcrone I have forwarded the screenshot to the OOI CI team and asked for the change.

**Comment by kerfoot** [comment]
OOI CI has informed me that the original will have to do.  Closing
