### ISSUE TITLE
Should 2014 glider data be missing?

### ISSUE THREAD

**Issue by rsignell-usgs** [rsignell-usgs/ooici-erddap#18]
@kerfoot , I read this article in Oceanus http://www.whoi.edu/oceanus/feature/pinocchios-nose and it talked about 2014 glider data from OOI showing surprising warm water intrusions on the shelf. 

I tried to find all the 2014 glider data on ERDDAP and came up with nothing:

https://erddap-uncabled.oceanobservatories.org/uncabled/erddap/search/advanced.html?page=1&itemsPerPage=1000&searchFor=&protocol=%28ANY%29&cdm_data_type=trajectory&institution=%28ANY%29&ioos_category=%28ANY%29&keywords=%28ANY%29&long_name=%28ANY%29&standard_name=%28ANY%29&variableName=%28ANY%29&maxLat=54&minLon=-85&maxLon=-57&minLat=33&minTime=2014-01-01&maxTime=2015-01-01

Is this expected?

**Comment by kerfoot** [comment]
@rsignell-usgs ERDDAP wasn't running in 2014 and, under the current plan, only data from active deployments is pushed to ERDDAP.  There are rumblings about adding historical deployments (both telemetered and recovered), but I have not been given the go ahead to do so yet.  Need to figure out space considerations first.

**Comment by rsignell-usgs** [comment]
@atkinsonlp, well,  that shoots down one idea I had for my ERDDAP demo at Ocean Sciences!
